name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        run: git checkout main

      - name: setup go toolchain
        run: go get github.com/google/go-github/v62

      - name: Build app
        run: scripts/buildprod.sh
